<?php
$dischi = [
    "success" => true,
    "response" => [
      [
        "poster" => "https://i1.wp.com/lostingroove.com/wp-content/uploads/2022/06/unnamed-63.jpg?fit=1000%2C1000&ssl=1",
        "title" => "Blood Moon",
        "author" => "RY X",
        "genre" => "Alt-Pop",
        "year" => "2022",
      ],
      [
        "poster" => "https://i.discogs.com/7IYk8oklzeizJp3NUnuGZe-Ntd42cT-EEOxEiuLsv88/rs:fit/g:sm/q:90/h:500/w:500/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzMDEx/OTcwLTE1NDY0NDI0/NzUtNDI4Ni5qcGVn.jpeg",
        "title" => "Requiem EP",
        "author" => "Apashe",
        "genre" => "Dubstep",
        "year" => "2018",
      ],
      [
        "poster" => "https://www.rockshock.it/wp-content/uploads/2022/05/moderat-recwensione-more-data-1200x1200.jpg",
        "title" => "More D4TA",
        "author" => "Moderat",
        "genre" => "Glitch",
        "year" => "2022",
      ],
      [
        "poster" => "https://www.termometropolitico.it/newmedia/2018/03/son-lux-brighter-wounds.jpg",
        "title" => "Brighter Wounds",
        "author" => "Son Lux",
        "genre" => "Post-rpck",
        "year" => "2018",
      ],
      [
        "poster" => "https://www.ansa.it/webimages/img_457x/2022/3/17/a44cdd965d4e5c3bc0d61c29469b9435.jpg",
        "title" => "Will of the people",
        "author" => "Muse",
        "genre" => "Post-rpck",
        "year" => "2022",
      ],
      [
        "poster" => "https://images-na.ssl-images-amazon.com/images/I/51sBr4IWDwL.jpg",
        "title" => "New Jersey",
        "author" => "Bon Jovi",
        "genre" => "Rock",
        "year" =>"1988",
      ],
      [
        "poster" => "https://img.discogs.com/vknPDdrqRbT92pNRX0W4I5N91jg=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/R-1246953-1448927086-6590.jpeg.jpg",
        "title" => "Live at Wembley 86",
        "author" => "Queen",
        "genre" => "Pop",
        "year" => "1992",
      ],
      [
        "poster" => "https://images-na.ssl-images-amazon.com/images/I/41JD3CW65HL.jpg",
        "title" => "Ten's Summoner's Tales",
        "author" => "Sting",
        "genre" => "Pop",
        "year" => "1993",
      ],
      [
        "poster" => "https://cdn2.jazztimes.com/2018/05/SteveGadd-800x723.jpg",
        "title" => "Steve Gadd Band",
        "author" => "Steve Gadd Band",
        "genre" => "Jazz",
        "year" => "2018",
      ],
      [
        "poster" => "https://images-na.ssl-images-amazon.com/images/I/810nSIQOLiL._SY355_.jpg",
        "title" => "Brave new World",
        "author" => "Iron Maiden",
        "genre" => "Metal",
        "year" => "2000",
      ],
      [
        "poster" => "https://upload.wikimedia.org/wikipedia/en/9/97/Eric_Clapton_OMCOMR.jpg",
        "title" => "One more car, one more raider",
        "author" => "Eric Clapton",
        "genre" => "Rock",
        "year" => "2002",
      ],
      [
        "poster" => "https://images-na.ssl-images-amazon.com/images/I/51rggtPgmRL.jpg",
        "title" => "Made in Japan",
        "author" => "Deep Purple",
        "genre" => "Rock",
        "year" => "1972",
      ],
      [
        "poster" => "https://images-na.ssl-images-amazon.com/images/I/81r3FVfNG3L._SY355_.jpg",
        "title" => "And Justice for All",
        "author" => "Metallica",
        "genre" => "Metal",
        "year" => "1988",
      ],
      [
        "poster" => "https://img.discogs.com/KOBsqQwKiNKH-q927oHMyVdDzSo=/fit-in/596x596/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-6406665-1418464475-6120.jpeg.jpg",
        "title" => "Hard Wired",
        "author" => "Dave Weckl",
        "genre" => "Jazz",
        "year" => "1994",
      ],
      [
        "poster" => "https://m.media-amazon.com/images/I/71K9CbNZPsL._SS500_.jpg",
        "title" => "Bad",
        "author" => "Michael Jacjson",
        "genre" => "Pop",
        "year" => "1987",
      ],
    ],
];
?>